litreview_app/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .forms import LoginForm
from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html',
                                                redirect_authenticated_user=True,
                                                authentication_form=LoginForm),
         name='login'),
    path('logout_page/logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'),
         name='logout'),
    path('logout_page/', views.logout_page, name='logout_page'),
    path('register/', views.register, name='register'),

    path('follow/<int:user_id>/', views.follow_user, name='follow_user'),
    path('unfollow/<int:user_id>/', views.unfollow_user, name='unfollow_user'),

    path('user_subscriptions/', views.user_subscriptions, name='user_subscriptions'),
    path('user_profile/<int:user_id>/', views.user_profile, name='user_profile'),
    path('user_update/', views.user_update, name='user_update'),
    path('search_user/', views.search_user, name='search_user'),
]

litreview_app/litreview_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('reviews.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

litreview_app/reviews/urls.py
from django.urls import path

from . import views

app_name = 'reviews'

urlpatterns = [
    path('', views.index, name='index'),

    path('review/<int:id>/', views.details, name='detail'),
    path('review/new_review/', views.new_review, name='new_review'),
    path('review/update_review/<int:id>/', views.update_review, name='update_review'),
    path('review/delete_review/<int:id>/', views.delete_review, name='delete_review'),
    path('review/user_reviews/', views.user_reviews, name='user_reviews'),

    path('review/ticket/new_ticket/', views.new_ticket, name='new_ticket'),
    path('review/ticket/<int:id>/', views.details_ticket, name='details_ticket'),
    path('review/update_ticket/<int:id>/', views.update_ticket, name='update_ticket'),
    path('review/delete_ticket/<int:id>/', views.delete_ticket, name='delete_ticket'),

    path('review/ticket/<int:id>/ticket_answer/', views.ticket_answer, name='ticket_answer'),
]

litreview_app/templates/layouts/partials/footer.html
<footer class="footer">
    <p class="text-center text-light">
        Copyright &copy; {% now 'Y' %} &middot; LitReview.
    </p>
</footer>

litreview_app/templates/layouts/partials/header.html
<nav class="navbar navbar-expand-lg bg-body-tertiary mb-4">
    <div class="container-fluid">
        <a class="navbar-brand text-black" href="{% url 'reviews:index' %}">LitReview</a>
        <p>Vous êtes connecté en tant que {{ request.user.username }}</p>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        </button>
        <div class="navbar navbar-light bg-light justify-content-between" id="navbarSupportedContent">
            <form action="{% url 'accounts:search_user' %}" method="get" class="d-flex ml-3">
                <input placeholder="Cherchez un utilisateur" class="form-control me-2" type="search" name="search">
                <button class="btn btn-outline m1-2" type="submit">Rechercher</button>
            </form>
            <ul class="navbar-nav mr-auto">
                {% if request.user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Publier un post
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="nav-link text-black" aria-current="page"
                                   href="{% url 'reviews:new_review' %}">Publier une critique</a></li>
                            <li><a class="nav-link text-black" aria-current="page"
                                   href="{% url 'reviews:new_ticket' %}">Publier un ticket</a></li>
                        </ul>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Votre profil
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="nav-link text-black" methods="post"
                                   href="{% url 'accounts:user_profile' request.user.id %}">Mes informations</a></li>
                            <li><a class="nav-link text-black" aria-current="page"
                                   href="{% url 'reviews:user_reviews' %}">Mes critiques</a></li>
                            <li><a class="nav-link text-black" methods="post"
                                   href="{% url 'accounts:user_subscriptions' %}">Mes abonnements</a></li>
                        </ul>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link text-black" methods="post" href="{% url 'accounts:logout_page' %}">Déconnection</a>
                    </li>

                {% else %}
                    <li class="nav-item">
                        <a class="nav-link text-black" href="{% url 'accounts:login' %}">Me connecter</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-black" href="{% url 'accounts:register' %}">M'inscrire</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>