litreview_app/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .forms import LoginForm
from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html',
                                                redirect_authenticated_user=True,
                                                authentication_form=LoginForm),
         name='login'),
    path('logout_page/logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'),
         name='logout'),
    path('logout_page/', views.logout_page, name='logout_page'),
    path('register/', views.register, name='register'),

    path('follow/<int:user_id>/', views.follow_user, name='follow_user'),
    path('unfollow/<int:user_id>/', views.unfollow_user, name='unfollow_user'),

    path('user_subscriptions/', views.user_subscriptions, name='user_subscriptions'),
    path('user_profile/<int:user_id>/', views.user_profile, name='user_profile'),
    path('user_update/', views.user_update, name='user_update'),
    path('search_user/', views.search_user, name='search_user'),
]

litreview_app/litreview_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('reviews.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

litreview_app/reviews/urls.py
from django.urls import path

from . import views

app_name = 'reviews'

urlpatterns = [
    path('', views.index, name='index'),

    path('review/<int:id>/', views.details, name='detail'),
    path('review/new_review/', views.new_review, name='new_review'),
    path('review/update_review/<int:id>/', views.update_review, name='update_review'),
    path('review/delete_review/<int:id>/', views.delete_review, name='delete_review'),
    path('review/user_reviews/', views.user_reviews, name='user_reviews'),

    path('review/ticket/new_ticket/', views.new_ticket, name='new_ticket'),
    path('review/ticket/<int:id>/', views.details_ticket, name='details_ticket'),
    path('review/update_ticket/<int:id>/', views.update_ticket, name='update_ticket'),
    path('review/delete_ticket/<int:id>/', views.delete_ticket, name='delete_ticket'),

    path('review/ticket/<int:id>/ticket_answer/', views.ticket_answer, name='ticket_answer'),
]

litreview_app/reviews/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import User


class Ticket(models.Model):
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    headline = models.fields.CharField(max_length=128, blank=True, null=True)
    body = models.fields.TextField(max_length=8192, blank=True, null=True)
    image = models.ImageField(upload_to='reviews_image/', height_field=None, width_field=None, null=True, blank=True)
    time_created = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    def __str__(self):
        return str(self.user)


class Review(models.Model):
    ticket = models.ForeignKey(to=Ticket, on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    headline = models.fields.CharField(max_length=128, blank=True, null=True)
    rating = models.fields.PositiveSmallIntegerField(
        blank=True, null=True,
        validators=[MinValueValidator(0), MaxValueValidator(5)])
    body = models.fields.TextField(max_length=8192, blank=True, null=True)
    image = models.ImageField(upload_to='reviews_image/', height_field=None, width_field=None, null=True, blank=True)
    time_created = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    def __str__(self):
        # return self.ticket.user
        return self.headline

litreview_app/reviews/forms.py
from django import forms
from django.core.validators import MaxValueValidator, MinValueValidator
from .models import Review, Ticket


class ReviewForm(forms.ModelForm):
    headline = forms.CharField(label='Titre', widget=forms.TextInput(attrs={'class': 'form-control'}))
    rating = forms.TypedChoiceField(
        label="Rating",
        coerce=int,
        widget=forms.RadioSelect,
        choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])
    body = forms.CharField(label='Commentaire',
                           required=False,
                           widget=forms.Textarea(attrs={'class': 'form-control'}))
    image = forms.ImageField(label='Image', required=False)

    class Meta:
        model = Review
        exclude = ['time_created', 'user', 'ticket']


class TicketForm(forms.ModelForm):
    headline = forms.CharField(label='Titre', widget=forms.TextInput(attrs={'class': 'form-control'}))
    body = forms.CharField(label='Commentaire',
                           required=False,
                           widget=forms.Textarea(attrs={'class': 'form-control'}))
    image = forms.ImageField(label='Image', required=False)

    class Meta:
        model = Ticket
        exclude = ['time_created', 'user']


class TicketAnswerForm(forms.ModelForm):
    headline = forms.CharField(label='Titre', widget=forms.TextInput(attrs={'class': 'form-control'}))
    rating = forms.TypedChoiceField(
        label="Rating",
        coerce=int,
        widget=forms.RadioSelect,
        choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])
    body = forms.CharField(label='Commentaire',
                           required=False,
                           widget=forms.Textarea(attrs={'class': 'form-control'}))
    image = forms.ImageField(label='Image', required=False)

    class Meta:
        model = Review
        exclude = ['time_created', 'user', 'ticket']

litreview_app/reviews/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import BadRequest
from django.contrib.auth.decorators import login_required
from .models import Review, Ticket
from .forms import ReviewForm, TicketForm, TicketAnswerForm
from django.http import Http404
from django.core.paginator import Paginator


@login_required
def index(request):
    reviews = Review.objects.order_by('-time_created').all()
    reviews_number = reviews.count()
    tickets = Ticket.objects.order_by('-time_created').all()
    tickets_number = tickets.count()
    user_reviews = set()
    for review in reviews:
        if review.user == request.user and review.ticket:
            user_reviews.add(review.ticket.id)

    combined = sorted(
        list(reviews) + list(tickets),
        key=lambda x: x.time_created,
        reverse=True
    )
    paginator = Paginator(combined, 5)
    page_number = request.GET.get('page')
    page_object = paginator.get_page(page_number)

    context = {
        'items': page_object,
        'reviews': reviews,
        'tickets': tickets,
        'reviews_number': reviews_number,
        'tickets_number': tickets_number,
        'user_reviews': user_reviews
    }
    return render(request, 'reviews/index.html', context)


@login_required
def details(request, id):
    review = Review.objects.get(id=id)
    context = {
        'review': review
    }
    return render(request, 'reviews/details.html', context)


@login_required
def new_review(request):
    form = ReviewForm()
    if request.method == 'POST':
        form = ReviewForm(request.POST, request.FILES)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.save()
            return redirect('reviews:index')
    context = {
        'form': form
    }
    return render(request, 'reviews/new_review.html', context)


@login_required
def update_review(request, id):
    review = Review.objects.get(id=id)
    if review.user == request.user:
        if request.method == 'POST':
            review_form = ReviewForm(request.POST, request.FILES, instance=review)
            if review_form.is_valid():
                review_form.save()
                return redirect('reviews:index')
        else:
            review_form = ReviewForm(instance=review)
    else:
        raise Http404

    context = {
        'review_form': review_form,
        'review': review,
    }
    return render(request, 'reviews/update_review.html', context)


@login_required
def delete_review(request, id):
    review = Review.objects.get(id=id)
    if review.user == request.user:
        review.delete()
        return redirect('reviews:index')
    else:
        raise Http404


@login_required
def user_reviews(request):
    reviews = Review.objects.filter(user=request.user).order_by('-time_created')
    reviews_number = reviews.count()
    context = {
        'reviews': reviews,
        'reviews_number': reviews_number
    }
    return render(request, 'reviews/user_reviews.html', context)


@login_required
def details_ticket(request, id):
    ticket = Ticket.objects.get(id=id)
    context = {
        'ticket': ticket
    }
    return render(request, 'reviews/details_ticket.html', context)


@login_required
def new_ticket(request):
    ticket_form = TicketForm()
    if request.method == 'POST':
        ticket_form = TicketForm(request.POST, request.FILES)
        if ticket_form.is_valid():
            ticket = ticket_form.save(commit=False)
            ticket.user = request.user
            if ticket_form.cleaned_data['image']:
                ticket.image = ticket_form.cleaned_data['image']
            ticket.save()
            return redirect('reviews:index')
    context = {
        'ticket_form': ticket_form
    }
    return render(request, 'reviews/new_ticket.html', context)


@login_required
def ticket_answer(request, id):
    ticket = Ticket.objects.get(id=id)
    if request.method == 'POST':
        review_form = TicketAnswerForm(request.POST, request.FILES)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.user = request.user
            review.ticket = ticket
            review.save()
            return redirect('reviews:index')
    else:
        review_form = ReviewForm()
    context = {
        'ticket': ticket,
        'review_form': review_form,
    }
    return render(request, 'reviews/ticket_answer.html', context)


@login_required
def update_ticket(request, id):
    ticket = Ticket.objects.get(id=id)
    if ticket.user == request.user:
        if request.method == 'POST':
            form = TicketForm(request.POST, request.FILES, instance=ticket)
            if form.is_valid():
                form.save()
                return redirect('reviews:index')
        else:
            form = TicketForm(instance=ticket)
    else:
        raise Http404

    context = {
        'form': form,
        'ticket': ticket,
    }
    return render(request, 'reviews/update_ticket.html', context)


@login_required
def delete_ticket(request, id):
    ticket = Ticket.objects.get(id=id)
    if ticket.user == request.user:
        ticket.delete()
        return redirect('reviews:index')
    else:
        raise Http404

litreview_app/reviews/templates/reviews/details.html
{% extends 'reviews/layouts/base.html' %}

{% block title %}Details{% endblock title %}

{% block body %}

    <h1>Détails</h1>

    <div class="card m-3 shadow">
        <div class="card-body">
            <h2 class="card-title">Critique de "{{ review.headline }}"</h2>
            {% if review.image %}
                <img src="{{ review.image.url }}" class="card-img-top" style="width: 10rem;" alt="...">
            {% endif %}
            <p>Note : {{ review.rating }}/5</p>
            <p class="card-text">{{ review.body }}</p>
        </div>
        {% if review.ticket.user.username %}
            <div class="card m-3 p-3 shadow">
                <h2>Ticket pour "{{ review.ticket.headline }}"</h2>
                {% if item.ticket.image %}
                    <img src="{{ review.ticket.image.url }}" class="card-img-top" style="width: 10rem;" alt="...">
                {% endif %}
                <p>{{ review.ticket.body }}</p>
                <p>Auteur : <a class="btn"
                               href="{% url 'accounts:user_profile' review.ticket.user.id %}">{{ review.ticket.user.username }}</a>
                </p>
            </div>
        {% endif %}

        <div class="card-footer">
            <a href="{% url 'reviews:index' %}" class="btn btn-primary">Retour</a>
            {% if review.user == request.user %}
                <a href="{% url 'reviews:update_review' review.id %}" class="btn btn-primary">Modifier</a>
                <a href="{% url 'reviews:delete_review' review.id %}" class="btn btn-danger">Supprimer</a>
            {% endif %}
        </div>
    </div>
    </div>
{% endblock body %}

litreview_app/reviews/templates/reviews/details_ticket.html
{% extends 'reviews/layouts/base.html' %}

{% block title %}Ticket{% endblock title %}

{% block body %}

    <h1>Ticket</h1>

    <div class="card mb-3">
        {% if ticket.image %}
            <img src="{{ ticket.image.url }}" class="card-img-top" style="width: 10rem;" alt="...">
        {% endif %}
        <div class="card-body">
            <h5 class="card-title">{{ ticket.headline }}</h5>
            <p class="card-text">{{ ticket.body }}</p>
            <p class="card-text"><small class="text-body-secondary">Last updated 3 mins ago</small></p>


            <div class="card-footer">
                <a href="{% url 'reviews:index' %}" class="btn btn-primary">Retour</a>
                {% if ticket.user == request.user %}
                    <a href="{% url 'reviews:update_ticket' ticket.id %}" class="btn btn-primary">Modifier</a>
                    <a href="{% url 'reviews:delete_ticket' ticket.id %}" class="btn btn-danger">Supprimer</a>
                {% else %}
                    <a href="{% url 'reviews:ticket_answer' ticket.id %}" class="btn btn-primary">Répondre</a>
                {% endif %}
            </div>

        </div>
    </div>
{% endblock body %}

litreview_app/reviews/templates/reviews/index.html
{% extends 'reviews/layouts/base.html' %}

{% block title %}Critiques{% endblock title %}

{% block body %}
    <h1>Flux</h1>

    {% load review_tags %}

    {% for item in items %}

        {% if item|instanceof:'Review' %}

            <div class="card shadow mb-3">
                <div class="card-body">
                    {% if item.ticket.user.username %}
                        <h2 class="card-title">Critique de "{{ item.ticket.headline }}"</h2>
                    {% else %}
                        <h2 class="card-title">Critique de "{{ item.headline }}"</h2>
                    {% endif %}
                    {% if item.image %}
                        <img src="{{ item.image.url }}" class="card-img-top" style="width: 10rem;" alt="...">
                    {% endif %}
                    <p class="card-text">Titre : {{ item.headline }}</p>
                    <p class="card-text">Commentaire de l'auteur : {{ item.body|truncatewords:20 }}</p>
                    <p class="card-text">Note de l'auteur : {{ item.rating }}/5</p>
                    <a href="{% url 'reviews:detail' item.id %}" class="btn btn-success">Voir plus</a>
                    {% if item.user == request.user %}
                        <a href="{% url 'reviews:update_review' item.id %}" class="btn btn-primary">Modifier</a>
                        <a href="{% url 'reviews:delete_review' item.id %}" class="btn btn-danger">Supprimer</a>
                    {% endif %}
                </div>

                {% if item.ticket and item.ticket.user.username %}
                    <div class="card m-3 p-3 shadow">
                        <h2>Ticket pour "{{ item.ticket.headline }}"</h2>
                        {% if item.ticket.image %}
                            <img src="{{ item.ticket.image.url }}" class="card-img-top" style="width: 10rem;" alt="...">
                        {% endif %}
                        <p>{{ item.ticket.body|truncatewords:20 }}</p>
                        <p>Auteur : <a class="btn"
                                       href="{% url 'accounts:user_profile' item.ticket.user.id %}">{{ item.ticket.user.username }}</a>
                        </p>
                    </div>
                {% endif %}

                <a class="btn" href="{% url 'accounts:user_profile' item.user.id %}">
                    <div class="card-footer">
                        Auteur : {{ item.user.username }}
                    </div>
                </a>
            </div>






        {% elif item|instanceof:'Ticket' %}
            <div class="card m-3 shadow">
                <div class="card-body">
                    <h2 class="card-title">Ticket pour "{{ item.headline }}"</h2>
                    {% if item.image %}
                        <img src="{{ item.image.url }}" class="card-img-top" style="width: 10rem;" alt="...">
                    {% endif %}
                    <p class="card-text">{{ item.body|truncatewords:20 }}</p>
                    <a href="{% url 'reviews:details_ticket' item.id %}" class="btn btn-success">Voir plus</a>
                    {% if item.user == request.user %}
                        <a href="{% url 'reviews:update_ticket' item.id %}" class="btn btn-primary">Modifier</a>
                        <a href="{% url 'reviews:delete_ticket' item.id %}" class="btn btn-danger">Supprimer</a>
                    {% else %}
                        {% if item.id not in user_reviews %}
                            <a href="{% url 'reviews:ticket_answer' item.id %}" class="btn btn-primary">Répondre</a>
                        {% else %}
                            <button class="btn btn-secondary" disabled>Répondu</button>
                        {% endif %}
                    {% endif %}
                </div>
                <a class="btn" href="{% url 'accounts:user_profile' item.user.id %}">
                    <div class="card-footer">
                        Auteur : {{ item.user.username }}
                    </div>
                </a>
            </div>
        {% endif %}

    {% endfor %}


    <nav>
        <ul class="pagination justify_content_center">
            {% if items.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="/?page={{ items.previous_page_number }}">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            {% endif %}
            <li class="page-item"><p class="page-link text-muted">Page {{ items.number }}
                sur {{ items.paginator.num_pages }}</p></li>
            {% if items.has_next %}
                <li class="page-item">
                    <a class="page-link" href="/?page={{ items.next_page_number }}">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endblock body %}

litreview_app/reviews/templates/reviews/new_review.html
{% extends 'reviews/layouts/base.html' %}

{% block title %}Nouvelle critique{% endblock title %}

{% block body %}
    <h1>Nouvelle critique</h1>
    <div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto">
                <form action="" method="post" enctype="multipart/form-data">
                    {% if form.subject.errors %}
                        {% for error in form.subject.errors %}
                            <p class="text-danger"><strong>{{ error }}</strong></p>
                        {% endfor %}
                    {% endif %}
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            {{ field.label_tag }}
                            {{ field }}
                            {% if field.help_text %}
                                <p class="help">{{ field.help_text }}</p>
                            {% endif %}
                            {% if form.subject.errors %}
                                {% for error in form.subject.errors %}
                                    <p class="text-danger"><strong>{{ error }}</strong></p>
                                {% endfor %}
                            {% endif %}
                        </div>
                    {% endfor %}
                    {% if review.image %}
                        <img  class="card-img-top" src="{{ review.image.url }}" style="width: 10rem;" alt="..."><br>
                    {% endif %}
                    <input type="submit" class="btn btn-primary" value="Publier la critique">
                </form>
            </div>
        </div>
    </div>
{% endblock body %}

litreview_app/reviews/templates/reviews/new_ticket.html
{% extends 'reviews/layouts/base.html' %}

{% block title %}New ticket{% endblock title %}

{% block body %}
    <h1>Demander une critique</h1>
    <div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto">
                <form action="" method="post" enctype="multipart/form-data">
                    {% if form.subject.errors %}
                        {% for error in form.subject.errors %}
                            <p class="text-danger"><strong>{{ error }}</strong></p>
                        {% endfor %}
                    {% endif %}
                    {% csrf_token %}
                    {% for field in ticket_form %}
                        <div class="form-group">
                            {{ field.label_tag }}
                            {{ field }}
                            {% if field.help_text %}
                                <p class="help">{{ field.help_text }}</p>
                            {% endif %}
                            {% if form.subject.errors %}
                                {% for error in form.subject.errors %}
                                    <p class="text-danger"><strong>{{ error }}</strong></p>
                                {% endfor %}
                            {% endif %}
                        </div>
                    {% endfor %}
                    <input type="submit" class="btn btn-primary" value="Publier ma demande de critique">
                </form>
            </div>
        </div>
    </div>
{% endblock body %}

litreview_app/reviews/templates/reviews/ticket_answer.html
{% extends 'reviews/layouts/base.html' %}

{% block title %}Ticket{% endblock title %}

{% block body %}
    <h1>Ticket</h1>
    <div class="card mb-3">
        vous répondez à : {{ ticket.user }}
        {% if ticket.image %}
            <img src="{{ ticket.image.url }}" class="card-img-top" style="width: 10rem;" alt="...">
        {% endif %}
        <div class="card-body">
            <h5 class="card-title">{{ ticket.headline }}</h5>
            <p class="card-text">{{ ticket.body }}</p>
            <p class="card-text"><small class="text-body-secondary">Last updated 3 mins ago</small></p>
        </div>
    </div>
    <h1>Nouvelle critique</h1>
    <div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in review_form %}
                        <div class="form-group">
                            {{ field.label_tag }}
                            {{ field }}
                            {% if field.help_text %}
                                <p class="help">{{ field.help_text }}</p>
                            {% endif %}
                            {% if field.errors %}
                                {% for error in field.errors %}
                                    <p class="text-danger"><strong>{{ error }}</strong></p>
                                {% endfor %}
                            {% endif %}
                        </div>
                    {% endfor %}
                    <input type="submit" class="btn btn-primary" value="Publier la critique">
                </form>
            </div>
        </div>
    </div>
{% endblock body %}

litreview_app/reviews/templates/reviews/update_review.html
{% extends 'reviews/layouts/base.html' %}

{% block title %}Modification critique{% endblock title %}

{% block body %}
    <h1>Modifiez votre critique de "{{ review.headline }}"</h1>
    <div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto">
                <form action="" method="post" enctype="multipart/form-data">
                    {% if form.subject.errors %}
                        {% for error in form.subject.errors %}
                            <p class="text-danger"><strong>{{ error }}</strong></p>
                        {% endfor %}
                    {% endif %}
                    {% csrf_token %}
                    {% for field in review_form %}
                        <div class="form-group">
                            {{ field.label_tag }}
                            {{ field }}
                            {% if field.help_text %}
                                <p class="help">{{ field.help_text }}</p>
                            {% endif %}
                            {% if form.subject.errors %}
                                {% for error in form.subject.errors %}
                                    <p class="text-danger"><strong>{{ error }}</strong></p>
                                {% endfor %}
                            {% endif %}
                        </div>
                    {% endfor %}
                    {% if review.image %}
                        <img class="card-img-top" src="{{ review.image.url }}" style="width: 10rem;" alt="..."><br>
                    {% endif %}
                    <input type="submit" class="btn btn-primary" value="Publier la modification">
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

litreview_app/reviews/templates/reviews/update_ticket.html
{% extends 'reviews/layouts/base.html' %}

{% block title %}Modification ticket{% endblock title %}

{% block body %}
    <h1>Modifiez votre ticket de "{{ ticket.headline }}"</h1>
    <div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto">
                <form action="" method="post" enctype="multipart/form-data">
                    {% if form.subject.errors %}
                        {% for error in form.subject.errors %}
                            <p class="text-danger"><strong>{{ error }}</strong></p>
                        {% endfor %}
                    {% endif %}
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            {{ field.label_tag }}
                            {{ field }}
                            {% if field.help_text %}
                                <p class="help">{{ field.help_text }}</p>
                            {% endif %}
                            {% if form.subject.errors %}
                                {% for error in form.subject.errors %}
                                    <p class="text-danger"><strong>{{ error }}</strong></p>
                                {% endfor %}
                            {% endif %}
                        </div>
                    {% endfor %}
                    {% if ticket.image %}
                        <img class="mb-3" src="{{ ticket.image.url }}" width="200"><br>
                    {% endif %}
                    <input type="submit" class="btn btn-primary" value="Publier la modification">
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

litreview_app/reviews/templates/reviews/user_reviews.html
{% extends 'reviews/layouts/base.html' %}

{% block title %}Critiques{% endblock title %}

{% block body %}

    <h1>Mes critiques :</h1>
    <ul>
        {% for review in reviews %}
            <div class="card m-3 shadow">
                <div class="card-body">
                    <h2 class="card-title">Critique de "{{ review.headline }}"</h2>
                    {% if review.image %}
                        <img src="{{ review.image.url }}" class="card-img-top" style="width: 10rem;" alt="...">
                    {% endif %}
                    <p class="card-text">{{ review.body|truncatewords:20 }}</p>
                    <a href="{% url 'reviews:detail' review.id %}" class="btn btn-success">Voir plus</a>
                    {% if review.user == request.user %}
                        <a href="{% url 'reviews:update_review' review.id %}" class="btn btn-primary">Modifier</a>
                        <a href="{% url 'reviews:delete_review' review.id %}" class="btn btn-danger">Supprimer</a>
                    {% endif %}
                </div>

                {% if review.ticket.user.username %}
                    <div class="card m-3 p-3 shadow">
                        <h2>Ticket pour "{{ review.ticket.headline }}"</h2>
                        {% if review.ticket.image %}
                            <img src="{{ review.ticket.image.url }}" class="card-img-top" style="width: 10rem;"
                                 alt="...">
                        {% endif %}
                        <p>{{ review.ticket.body }}</p>
                        <p>Auteur : <a class="btn"
                                       href="{% url 'accounts:user_profile' review.ticket.user.id %}">{{ review.ticket.user.username }}</a>
                        </p>
                    </div>
                {% endif %}
                <div class="card-footer">
                    {{ review.user.username }}
                </div>
            </div>
        {% endfor %}
    </ul>
{% endblock body %}