litreview_app/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .forms import LoginForm
from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html',
                                                redirect_authenticated_user=True,
                                                authentication_form=LoginForm),
         name='login'),
    path('logout_page/logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'),
         name='logout'),
    path('logout_page/', views.logout_page, name='logout_page'),
    path('register/', views.register, name='register'),

    path('follow/<int:user_id>/', views.follow_user, name='follow_user'),
    path('unfollow/<int:user_id>/', views.unfollow_user, name='unfollow_user'),

    path('user_subscriptions/', views.user_subscriptions, name='user_subscriptions'),
    path('user_profile/<int:user_id>/', views.user_profile, name='user_profile'),
    path('user_update/', views.user_update, name='user_update'),
    path('search_user/', views.search_user, name='search_user'),
]

litreview_app/litreview_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('reviews.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

litreview_app/reviews/urls.py
from django.urls import path

from . import views

app_name = 'reviews'

urlpatterns = [
    path('', views.index, name='index'),

    path('review/<int:id>/', views.details, name='detail'),
    path('review/new_review/', views.new_review, name='new_review'),
    path('review/update_review/<int:id>/', views.update_review, name='update_review'),
    path('review/delete_review/<int:id>/', views.delete_review, name='delete_review'),
    path('review/user_reviews/', views.user_reviews, name='user_reviews'),

    path('review/ticket/new_ticket/', views.new_ticket, name='new_ticket'),
    path('review/ticket/<int:id>/', views.details_ticket, name='details_ticket'),
    path('review/update_ticket/<int:id>/', views.update_ticket, name='update_ticket'),
    path('review/delete_ticket/<int:id>/', views.delete_ticket, name='delete_ticket'),

    path('review/ticket/<int:id>/ticket_answer/', views.ticket_answer, name='ticket_answer'),
]

litreview_app/accounts/models.py
from django.contrib.auth.models import User
from django.conf import settings
from django.db import models


class Subscription(models.Model):
    subscriber = models.ForeignKey(User, related_name='subscriptions', on_delete=models.CASCADE)
    subscribed_to = models.ForeignKey(User, related_name='subscribers', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('subscriber', 'subscribed_to')

    def __str__(self):
        return f'{self.subscriber} -> {self.subscribed_to}'


class UserFollows(models.Model):
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='following')
    followed_user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='followed_by')

    class Meta:
        unique_together = ('user', 'followed_user',)

litreview_app/accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):

    username = forms.CharField(label='Nom', widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))
    password = forms.CharField(label='Mot de passe', widget=forms.PasswordInput(attrs={
        'class': 'form-control'
    }))


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Nom', help_text='Entrez votre pseudo', widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))
    email = forms.EmailField(label='E-mail', widget=forms.EmailInput(attrs={
        'class': 'form-control'
    }))
    password1 = forms.CharField(label='Mot de passe', widget=forms.PasswordInput(attrs={
        'class': 'form-control'
    }))
    password2 = forms.CharField(label='Confirmez votre mot de passe', widget=forms.PasswordInput(attrs={
        'class': 'form-control'
    }))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class UpdateUserForm(forms.ModelForm):
    username = forms.CharField(label='Nom', widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={
        'class': 'form-control'
    }))

    class Meta:
        model = User
        fields = ('username', 'email')

litreview_app/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import RegisterUserForm, UpdateUserForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from .models import Subscription, UserFollows


# CRÉATION D'UTILISATEURS
def register(request):
    if request.user.is_authenticated:
        return redirect('reviews:index')
    if request.method == 'POST':
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('reviews:index')
    else:
        form = RegisterUserForm()

    context = {
        'form': form
    }

    return render(request, 'accounts/register.html', context)


def logout_page(request):
    return render(request, 'accounts/logout_page.html')


# CRÉATION DU SYSTÈME D'ABONNEMENT
@login_required
def user_subscriptions(request):
    user = request.user
    subscriptions = UserFollows.objects.filter(user=user)
    subscribers = UserFollows.objects.filter(followed_user=user)

    context = {
        'subscriptions': subscriptions,
        'subscribers': subscribers,
    }
    return render(request, 'accounts/user_subscriptions.html', context)


@login_required
def follow_user(request, user_id):
    user_to_follow = get_object_or_404(User, id=user_id)
    if user_to_follow == request.user:
        messages.error(request, "Vous ne pouvez pas vous suivre vous-même.")
        return redirect('user_profile', user_id=user_id)

    follow, created = UserFollows.objects.get_or_create(user=request.user, followed_user=user_to_follow)
    if created:
        messages.success(request, f'Vous suivez maintenant {user_to_follow.username}.')
    else:
        messages.info(request, f'Vous suivez déjà {user_to_follow.username}.')
    return redirect('accounts:user_profile', user_id=user_id)


@login_required
def unfollow_user(request, user_id):
    user_to_unfollow = get_object_or_404(User, id=user_id)
    UserFollows.objects.filter(user=request.user, followed_user=user_to_unfollow).delete()
    messages.success(request, f'Vous ne suivez plus {user_to_unfollow.username}.')
    return redirect('accounts:user_profile', user_id=user_id)


@login_required
def user_profile(request, user_id):
    user = get_object_or_404(User, id=user_id)
    is_following = UserFollows.objects.filter(user=request.user, followed_user=user).exists()

    context = {
        'user_profile': user,
        'is_following': is_following,
    }
    return render(request, 'accounts/user_profile.html', context)


@login_required
def user_update(request):
    if request.method == 'POST':
        form = UpdateUserForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:user_profile', user_id=request.user.id)
    else:
        form = UpdateUserForm(instance=request.user)

    context = {
        'form': form
    }
    return render(request, 'accounts/update_user.html', context)


# BARRE DE RECHERCHE
@login_required
def search_user(request):
    search = request.GET.get('search')
    users = User.objects.filter(username__icontains=search)
    context = {
        'search': search,
        'users': users,
    }
    return render(request, 'accounts/search_user.html', context)

litreview_app/accounts/templates/accounts/login.html
{% extends 'reviews/layouts/base.html' %}

{% block title %}Login{% endblock title %}

{% block body %}
    <h1>Me connecter</h1>
    <div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    {% if form.non_field.errors %}
                        {% for error in form.subject.errors %}
                            <p class="text-danger"><strong>{{ error }}</strong></p>
                        {% endfor %}
                    {% endif %}
                    {% for field in review_form %}
                        <div class="form-group">
                            {{ field.label_tag }}
                            {{ field }}
                            {% if field.help_text %}
                                <p class="help">{{ field.help_text }}</p>
                            {% endif %}
                            {% if form.subject.errors %}
                                {% for error in form.subject.errors %}
                                    <p class="text-danger"><strong>{{ error }}</strong></p>
                                {% endfor %}
                            {% endif %}
                        </div>
                    {% endfor %}
                    <input type="submit" class="btn btn-primary" value="Je me connecte !">
                </form>
            </div>
        </div>
    </div>
{% endblock body %}

litreview_app/accounts/templates/accounts/logout_page.html
{% extends 'reviews/layouts/base.html' %}

{% block title %}Déconnexion{% endblock title %}

{% block body %}
    <h1>Déconnexion</h1>
    <div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto">
                <form method="post" action="{% url 'accounts:logout' %}">
                    {% csrf_token %}
                    <input type="submit" class="btn btn-primary" value="Je me déconnecte !">
                </form>
            </div>
        </div>
    </div>
{% endblock body %}

litreview_app/accounts/templates/accounts/register.html
{% extends 'reviews/layouts/base.html' %}

{% block title %}Login{% endblock title %}

{% block body %}
    <h1>M'inscrire</h1>
    <div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto">
                <form action="" method="post" enctype="multipart/form-data">
                    {{ form.as_p }}
                    {% csrf_token %}
                    {% if form.non_field.errors %}
                        {% for error in form.subject.errors %}
                            <p class="text-danger"><strong>{{ error }}</strong></p>
                        {% endfor %}
                    {% endif %}
                    {% for field in review_form %}
                        <div class="form-group">
                            {{ field.label_tag }}
                            {{ field }}
                            {% if field.help_text %}
                                <p class="help">{{ field.help_text }}</p>
                            {% endif %}
                            {% if form.subject.errors %}
                                {% for error in form.subject.errors %}
                                    <p class="text-danger"><strong>{{ error }}</strong></p>
                                {% endfor %}
                            {% endif %}
                        </div>
                    {% endfor %}
                    <input type="submit" class="btn btn-primary" value="Je m'inscrit !">
                </form>
            </div>
        </div>
    </div>
{% endblock body %}

litreview_app/accounts/templates/accounts/search_user.html
{% extends 'reviews/layouts/base.html' %}

{% block title %}Profil de {{ user_profile.username }}{% endblock title %}

{% block body %}

    <h1 class="text-center">Résultats :</h1>

    {% for user in users %}
        <div class="card mb-3">
            <div class="card-body">
                <h3>Nom d'utilisateur : {{ user.username }}</h3>
                <h3>Email : {{ user.email }}</h3>
                {% if user_profile.id == request.user.id %}
                    <a class="btn btn-primary" href="{% url 'accounts:user_update' %}">Modifier mes informations</a>
                {% else %}
                    {% if not is_following %}
                        <a class="btn btn-primary m" href="{% url 'accounts:follow_user' user.id %}">Suivre</a>
                    {% else %}
                        <a class="btn btn-danger" href="{% url 'accounts:unfollow_user' user.id %}">Ne plus suivre</a>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    {% endfor %}


{% endblock body %}

litreview_app/accounts/templates/accounts/update_user.html
{% extends 'reviews/layouts/base.html' %}

{% block title %}Modifier mes informations personnelles{% endblock title %}

{% block body %}
    <h1>Modifier mes informations personnelles</h1>

    <div class="card mb-3">
        <h2>Modifier les informations personnelles</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Enregistrer les modifications</button>
        </form>
    </div>
{% endblock body %}

litreview_app/accounts/templates/accounts/user_profile.html
{% extends 'reviews/layouts/base.html' %}

{% block title %}Profil de {{ user_profile.username }}{% endblock title %}

{% block body %}

    <h1>Profil de {{ user_profile.username }}</h1>

    <div class="card mb-3">
        <div class="card-body">
            <h3>Nom d'utilisateur : {{ user_profile.username }}</h3>
            <h3>Email : {{ user_profile.email }}</h3>
            {% if user_profile.id == request.user.id %}
                <a class="btn btn-primary" href="{% url 'accounts:user_update' %}">Modifier mes informations</a>
            {% else %}
                {% if not is_following %}
                    <a class="btn btn-primary" href="{% url 'accounts:follow_user' user_profile.id %}">Suivre</a>
                {% else %}
                    <a class="btn btn-danger" href="{% url 'accounts:unfollow_user' user_profile.id %}">Ne plus
                        suivre</a>
                {% endif %}
            {% endif %}
        </div>
    </div>

{% endblock body %}

litreview_app/accounts/templates/accounts/user_subscriptions.html
{% extends 'reviews/layouts/base.html' %}

{% block title %}Mes abonnements{% endblock title %}

{% block body %}
    <h1>Mes abonnements</h1>

    <h2>Abonnements</h2>
    <ul>
        {% for subscription in subscriptions %}
            <li>{{ subscription.followed_user.username }}</li>
        {% endfor %}
    </ul>

    <h2>Abonnés</h2>
    <ul>
        {% for subscriber in subscribers %}
            <li>{{ subscriber.user.username }}</li>
        {% endfor %}
    </ul>
{% endblock body %}